// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjweehmxbizrcmeuujvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhqd2VlaG14Yml6cmNtZXV1anZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzNjk1NDgsImV4cCI6MjA3NTk0NTU0OH0.y1hn6jgRcqwwG0oFurqZw1-GtLzatmi2IHhxdHuFjKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});